version: '3.8'

services:
  frontend:
    build: frontend/
    container_name: verification-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run serve
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
