version: '3.8'

services:
  frontend:
    build: frontend/
    container_name: verification-frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    command: yarn serve
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: backend/
    container_name: verification-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app:cached
      - ./backend/tmp/:/app/tmp:cached
      - bundle_path:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    command: rails s -b 0.0.0.0
    stdin_open: true
    tty: true

  db:
    image: postgres:16
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./backend/persistence/postgres:/var/lib/postgresql/data/pgdata:delegated
    ports:
      - 45432:5432

volumes:
  bundle_path:
